### ISSUE TITLE
Harshom component

### ISSUE THREAD

**Issue by Grammarsalad** [RedChimera/semiOverhaul-v1.32#18]
Not installing

**Comment by Grammarsalad** [comment]
[image](https://user-images.githubusercontent.com/25755713/40888072-e9f4854e-671f-11e8-94aa-0eb094159dd5.png)

**Comment by semiticgod** [comment]
The component installs fine. It gives an error message, but the "INSTALLED WITH WARNINGS" thing at the end is meaningless. The dialogue is updated properly and you can view the changes in Near Infinity.

The cause of the "bug" is a trigger that WeiDU doesn't recognize but does not prevent installation. That trigger, SeeDead or something to that effect, comes from the vanilla game's dialog file. If you decompile the original .dlg file into a .d file, then recompile it back into a .dlg file, you'll get the same result even if you didn't change Harshom's dialog at all.

It's a vanilla "bug" that appears to have no adverse effects.

**Comment by Grammarsalad** [comment]
oh, cool
