### ISSUE TITLE
Improved Initiative Feat

### ISSUE THREAD

**Issue by semiticgod** [RedChimera/semiOverhaul-v1.32#19]
The Improved Initiative feat has always been bugged. Choosing the feat does absolutely nothing, when it's supposed to grant a +1 bonus to casting time and weapon speed factor. The only existing fix is the II_FIX mod, which creates a custom potion that applies the bonuses, which the player can create via the console. The fix works, but this is unsatisfactory for EE.

Theoretically, we could apply the bonuses from Improved Initiative via a spell, item, dialog or script. However, there appears to be no way to check if the player possesses a feat. I see no such triggers in the IDS files. Whichever method we might use, the fix would grant the bonuses to all characters, even those without the feat.

GemRB has custom spells with the effects of certain feats, but to my knowledge, we cannot reach any internal spell files that the feats apply.

To my knowledge, we have no way of changing the feat requirements to prevent players from choosing it to begin with. The FEATREQ.2da can get found at GemRB, but placing it in the override folder and editing it appears to do nothing.

I suggest we simply remove the feat from the game.

**Comment by Grammarsalad** [comment]
Does it count as a spell? Does it have an entry in spells.ids?

**Comment by semiticgod** [comment]
@Grammarsalad: Doesn't look like it. The search function shows no instance of "INITIATIVE" in any IDS, BCS, DLG, or 2DA file.

**Comment by Grammarsalad** [comment]
Damn...looks like the only thing to do is to get rid of it...

**Comment by OlvynChuru** [comment]
This problem is solved. Improved Initiative now correctly grants -1 casting time (it also now grants -4 attack speed factor because -1 speed factor is barely anything).
