### ISSUE TITLE
Spells revisions cause game to crash on level up

### ISSUE THREAD

**Issue by MaciejReszotnik** [RedChimera/semiOverhaul-v1.32#57]
Hi there. Thanks for the mod.

I installed GOG version of IWD 2 (ver 2.01) and your ee pack on top of it. It seems that spell revision component causes the game to crash when you create a new character or when you level up old one.

For example, the following error comes up: 
![obraz](https://user-images.githubusercontent.com/20501058/80754601-95225380-8b2f-11ea-9dad-daba5b4004d7.png)

Uninstalling this component fixes the issue but causes others. I would gladly enjoy playing ID2 with your fix, but cannot continue. BTW, do you need help with this one? Is there any way we could get know-how on how to fix this ourselves?

**Comment by OlvynChuru** [comment]
Hi!

The new version of IWD2EE fixes this issue.
