### ISSUE TITLE
Elder Brain dialogue

### ISSUE THREAD

**Issue by semiticgod** [RedChimera/semiOverhaul-v1.32#7]
The Elder Brain dialogue needs script commands to make all critters in the area neutral if the player successfully intimidates the brain.

Abdoshanheth needs a dialog that allows the player to intimidate him into neutrality.

**Comment by semiticgod** [comment]
The Elder Brain is 53ELDERB.cre, with the dialog 53ELDER.d. The area is AR5302. Abdoshanheth is 53ABDOSH, with the dialog 53ABDOSH.DLG (I will edit his dialog at some point and add the .d file to the Google Drive). The intimidate option is at BEGIN 10.

The Elder Brain's allies include:

53ABDOSH
53DESATH
53DEEPTH (should already be neutral)
53DRWITH
53DRFIT2
53DRFITH
53ECKTAR
53FGOLEM
53FOMOTH
53GALOOM
53LIGGEN
53MGOLEM
53MINOTH
53MORHIZ
53OOLAY
53GOLIMH (Enhanced Flesh Golem. I'm not sure I've ever seen this one; I thought the enhanced golem was only found at Imphraili's place)
53ZEPH

If the player speaks to the brain a second time after intimidating it, it goes hostile again. This should also include commands to turn the rest of the place hostile if necessary (excluding the deep gnome thralls, 53DEEPTH). This is at BEGIN 9.

**Comment by semiticgod** [comment]
I've added an option to intimidate the Elder Brain via Abdoshanheth's dialog. In 53ABDOSH.d, the first response to BEGIN 3 leads to the relevant line in the Elder Brain's dialog. I have already uploaded the file to Github and added a COPY line to the relevant TPA.

**Comment by Grammarsalad** [comment]
Added SetGlobal("SCAREDYBRAIN","GLOBAL",1) to intimidate option in 53ELDR.D
